// Generated by CoffeeScript 1.8.0
(function() {
  var Rrq, fs, path, util;

  fs = require('fs');

  path = require('path');

  util = require('util');

  Rrq = (function() {
    function Rrq() {}

    Rrq.projectRoot = function() {
      var dir, file, files, _i, _len;
      dir = __dirname;
      while (1) {
        files = fs.readdirSync(dir);
        for (_i = 0, _len = files.length; _i < _len; _i++) {
          file = files[_i];
          if (file === '.rrqrc') {
            return dir;
          }
        }
        dir = this.upperDir(dir);
        if (dir === '/') {
          throw new Error('Please smake a [.pddrc] file in the project root directory');
        }
      }
    };

    Rrq.upperDir = function(dirPath) {
      var arr, i, newdir, _i, _ref;
      arr = dirPath.split(path.sep);
      newdir = '/';
      for (i = _i = 1, _ref = arr.length - 1; 1 <= _ref ? _i < _ref : _i > _ref; i = 1 <= _ref ? ++_i : --_i) {
        newdir = path.join(newdir, arr[i]);
      }
      return newdir;
    };

    Rrq.require2 = function(_path) {
      var root;
      root = Rrq.projectRoot();
      return require(path.join(root, _path));
    };

    Rrq.requirePath = function(dirname, directoryPath) {
      return path.relative(dirname, path.join(Rrq.projectRoot(), directoryPath));
    };

    return Rrq;

  })();

  module.exports = Rrq;

}).call(this);
