// Generated by CoffeeScript 1.8.0

/*
v1.1.0
2015/01/09 17:10
 */

(function() {
  var Rrq, fs, path, util;

  fs = require('fs');

  path = require('path');

  util = require('util');

  Rrq = (function() {
    var _confpath;

    function Rrq() {}

    _confpath = '';

    Rrq.projectRoot = function() {
      var dir, file, files, _i, _len;
      dir = __dirname;
      while (1) {
        files = fs.readdirSync(dir);
        for (_i = 0, _len = files.length; _i < _len; _i++) {
          file = files[_i];
          if (/^\.rrq/.test(file)) {
            _confpath = file;
            return dir;
          }
        }
        dir = path.dirname(dir);
        if (dir === '/') {
          throw new Error('Please make a [.rrqrc] file in the project root directory');
        }
      }
    };

    Rrq.root = Rrq.projectRoot;

    Rrq.confpath = function() {
      var r;
      r = this.root();
      return path.join(r, _confpath);
    };

    Rrq.require2 = function(_path) {
      var root;
      root = Rrq.projectRoot();
      return require(path.join(root, _path));
    };

    Rrq.require = Rrq.require2;

    Rrq.requirePath = function(dirname, directoryPath) {
      var p;
      p = path.relative(dirname, path.join(Rrq.projectRoot(), directoryPath));
      if (!/^\.\./.test(p)) {
        p = './' + p;
      }
      return p;
    };

    return Rrq;

  })();

  module.exports = Rrq;

}).call(this);
