// Generated by CoffeeScript 1.8.0
(function() {
  var Rrq, fs, path, util;

  fs = require('fs');

  path = require('path');

  util = require('util');

  Rrq = (function() {
    function Rrq() {}

    Rrq.projectRoot = function() {
      var dir, file, files, _i, _len;
      dir = __dirname;
      while (1) {
        files = fs.readdirSync(dir);
        for (_i = 0, _len = files.length; _i < _len; _i++) {
          file = files[_i];
          if (file === '.rrqrc') {
            return dir;
          }
        }
        dir = this.upperDir(dir);
        if (dir === '/') {
          throw new Error('Please make a [.rrqrc] file in the project root directory');
        }
      }
    };

    Rrq.upperDir = function(dirPath) {
      var arr;
      dirPath = path.normalize(dirPath);
      arr = dirPath.split(path.sep);
      if (arr[arr.length - 1] === '') {
        arr.pop();
      }
      arr.pop();
      return arr.join(path.sep);
    };

    Rrq.require2 = function(_path) {
      var root;
      root = Rrq.projectRoot();
      return require(path.join(root, _path));
    };

    Rrq.requirePath = function(dirname, directoryPath) {
      return path.relative(dirname, path.join(Rrq.projectRoot(), directoryPath));
    };

    return Rrq;

  })();

  module.exports = Rrq;

}).call(this);
